# Makefile for ONICS scripts

all:
	@echo "Run ./configure in the top level directory first"
	@exit 1


clean:
	rm -f onics_stdproto_list.txt onics_proto.7 enum_proto

veryclean: clean
	rm -f makefile
