#!/bin/sh

usage() {
	echo "usage: $0 [-f file] [stmt1 stmt2 ...]">&2
	exit 1
}

PMLSCRIPT="
	import \"std.pml\";
	{
	pkt_ins_d(0, str_addr(pkt.payload), 14);
	parse_push_front(0, @eth);
"

INFILE=""

if [ $# -gt 0 ]
then
	[ "$1" = "-h" ] && usage
	if [ "$1" = "-f" ]
	then
		[ $# -lt 2 ] && usage
		INFILE="$2"
		shift
		shift
	fi
fi

for S
do
	PMLSCRIPT="$PMLSCRIPT
$S"
done

PMLSCRIPT="$PMLSCRIPT
	fix_dltype(0);
	fix_lens(0);
}"

exec pml -e "$PMLSCRIPT" $INFILE
