#!/bin/sh
#
# ONICS
# Copyright 2016
# Christopher Adam Telfer
#
# ipwrap - Wrap a packet in an IP header.
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

usage() {
	echo "usage: $0 [-f file] [stmt1 stmt2 ...]">&2
	exit 1
}

IPATH=${IPATH:-}

PMLSCRIPT="
	{
	ip_wrap();
"

INFILE=""

if [ $# -gt 0 ]
then
	[ "$1" = "-h" ] && usage
	if [ "$1" = "-f" ]
	then
		[ $# -lt 2 ] && usage
		INFILE="$2"
		shift
		shift
	fi
fi

for S
do
	PMLSCRIPT="$PMLSCRIPT
$S"
done

PMLSCRIPT="$PMLSCRIPT
	fix_lens(0);
	fix_csums(0);
}"

exec pml $IPATH -ie "$PMLSCRIPT" $INFILE
