#!/bin/sh
#
# ONICS
# Copyright 2015
# Christopher Adam Telfer
#
# mkarp - Generate an ARP-over-Ethernet packet.
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

usage() { 
	echo "usage: mkarp [MODSTR1...]"
	exit 1
}

START='
	parse_push_front(0, @arp);
	parse_push_front(0, @eth);

	eth.src = 02:00:00:00:00:01;
	eth.dst = ff:ff:ff:ff:ff:ff;
	arp.sndpraddr = 192.168.0.1;
	arp.sndhwaddr = 02:00:00:00:00:01;
	arp.trgpraddr = 192.168.0.2;
'

pml -e "import \"std.pml\";
        BEGIN { pkt_new(0, 0); $START $* send 0; }"
