#!/bin/sh

SPORT=${SPORT:-12345}
DPORT=${DPORT:-80}
SADDR=${SADDR:-192.168.0.1}
DADDR=${DADDR:-192.168.0.2}
SEQ=${SEQ:-0x12345678}
ACK=${ACK:-0x87654321}


PMLSCRIPT="{
	pkt_ins_d(0, str_addr(&pkt.payload), 54);
	parse_push_front(0, @tcp);
	parse_push_front(0, @ip);
	parse_push_front(0, @eth);

	ip.saddr = ${SADDR};
	ip.daddr = ${DADDR};
	ip.ttl = 64;
	tcp.sport = ${SPORT};
	tcp.dport = ${DPORT};
	tcp.ack = 1;
	tcp.psh = 1;
	tcp.seqn = ${SEQ};
	tcp.ackn = ${ACK};

	fix_dltype(0);
	fix_all_len(0);
	fix_all_csum(0);
}"

if [ $# -gt 0 ]
then
	exec pml -e "$PMLSCRIPT" < $1
else
	exec pml -e "$PMLSCRIPT" 
fi
