#!/bin/sh
#
# ONICS
# Copyright 2016
# Christopher Adam Telfer
#
# mkudp6 - Generate a UDP/IPv6/Ethernet packet.
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

usage() { 
	echo "usage: mkudp [(FILE|-|--) [MODSTR1...]]"
	echo "	FILE indicates to read payload from FILE"
	echo "	\"-\" indicates to read payload from standard input"
	echo "	\"--\" indicates no payload but modification strings follow"
	exit 1
}

IPATH=${IPATH:-}

START='
	pdu_insert(pkt, @udp);
	pdu_insert(pkt, @ip6);
	pdu_insert(pkt, @eth);

	eth.src = 02:00:00:00:00:01;
	eth.dst = 02:00:00:00:00:02;
	ip6.saddr = fe80::1;
	ip6.daddr = fe80::2;
	ip6.hoplim = 64;
	udp.sport = 12345;
	udp.dport = 53;
'

END='
	fix_lens(0);
	fix_csums(0);
'

if [ $# -gt 0 -a "$1" != "--" ] 
then
	[ "$1" = "-h" ] && usage
	if [ "$1" != "-" ] 
	then
		F=$1
		shift
		rawpkt $F | pml $IPATH -ie "{ $START $* $END }"
	else
		shift
		rawpkt | pml $IPATH -ie "{ $START $* $END }"
	fi
else
	if [ $# -gt 0 ] ; then shift ; fi
	pml $IPATH -ie "BEGIN { pkt_new(0, 0); $START $* $END send 0; }"
fi

