#!/bin/sh

usage() { 
	echo "usage: mkudp [(FILE|-|--) [MODSTR1...]]"
	echo "	FILE indicates to read payload from FILE"
	echo "	\"-\" indicates to read payload from standard input"
	echo "	\"--\" indicates no payload but modification strings follow"
	exit 1
}

START='
	parse_push_front(0, @udp);
	parse_push_front(0, @ip6);
	parse_push_front(0, @eth);

	eth.src = 02:00:00:00:00:01;
	eth.dst = 02:00:00:00:00:02;
	ip6.saddr = fe80::1;
	ip6.daddr = fe80::2;
	ip6.hoplim = 64;
	udp.sport = 12345;
	udp.dport = 53;
'

END='
	fix_dltype(0);
	fix_lens(0);
	fix_csums(0);
'

if [ $# -gt 0 -a "$1" != "--" ] 
then
	[ "$1" = "-h" ] && usage
	if [ "$1" != "-" ] 
	then
		F=$1
		shift
		rawpkt $F | pml -e "{ $START $* $END }"
	else
		shift
		rawpkt | pml -e "{ $START $* $END }"
	fi
else
	if [ $# -gt 0 ] ; then shift ; fi
	pml -e "BEGIN { pkt_new(0, 0); $START $* $END send 0; }"
fi

