#!/bin/sh
#
# ONICS
# Copyright 2013-2015
# Christopher Adam Telfer
#
# pcount - Count the packets in a file/stream.
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DROP=" drop; "
STATUS=""
OUTMSG='print C, " total packets and ", B, " total bytes.";'

usage() {
	echo "usage: $0 [-q] [-s|--status INTERVAL] [INFILE]" >&2
	echo "       $0 [-q] [-s|--status INTERVAL] [-p|--pass] [INFILE [OUTFILE]]" >&2
	exit 1
}

if [ $# -gt 0 ]
then
	[ "$1" = "-h" -o "$1" = "--help" ] && usage

	if [ "$1" = "-q" ]
	then
		OUTMSG="print C;"
		shift
	fi

	if [ "$1" = "-s" -o "$1" = "--status" ]
	then
		[ $# -lt 2 ] && usage
		INTERVAL=$2
		INTERVAL=`expr $INTERVAL \* 1000`
		STATUS="int T = 0; 
			TICK { 
				T = T + 1;
				if (T % $INTERVAL == 0) {
					print C, \" packets/\",
					      B, \" bytes seen so far.\";
				}
			}"
		shift
		shift
	fi

	if [ "$1" = "-p" -o "$1" = "--pass" ]
	then
		DROP=""
		shift
		[ $# -gt 2 ] && usage
	else
		[ $# -gt 1 ] && usage
	fi
fi

SCRIPT="int C = 0;
        int B = 0;
	{ C = C + 1; B = B + str_len(pkt.payload); $DROP }
	$STATUS
	END { $OUTMSG }"

if [ -z "$DROP" ]
then
	exec pml -e "$SCRIPT" $* 
else
	exec pml -e "$SCRIPT" $* 2>&1 >/dev/null
fi
