#!/bin/sh

DROP=" drop; "
STATUS=""

usage() {
	echo "usage: $0 [-s|--status INTERVAL] [INFILE]" >&2
	echo "       $0 [-s|--status INTERVAL] [-p|--pass] [INFILE [OUTFILE]]" >&2
	exit 1
}

if [ $# -gt 0 ]
then
	[ "$1" = "-h" -o "$1" = "--help" ] && usage

	if [ "$1" = "-s" -o "$1" = "--status" ]
	then
		[ $# -lt 2 ] && usage
		INTERVAL=$2
		INTERVAL=`expr $INTERVAL \* 1000`
		STATUS="int T = 0; 
			TICK { 
				T = T + 1;
				if (T % $INTERVAL == 0) {
					print C, \" packets seen so far.\n\";
				}
			}"
		shift
		shift
	fi

	if [ "$1" = "-p" -o "$1" = "--pass" ]
	then
		DROP=""
		shift
		[ $# -gt 2 ] && usage
	else
		[ $# -gt 1 ] && usage
	fi
fi

SCRIPT="int C = 0;
	{ C = C + 1; $DROP }
	$STATUS
	END { print C, \" total packets seen.\n\"; }"

if [ -z "$DROP" ]
then
	exec pml -e "$SCRIPT" $* 
else
	exec pml -e "$SCRIPT" $* 2>&1 >/dev/null
fi
