#!/bin/sh

DROP=" drop; "

usage() {
	echo "usage: $0 [INFILE]" >&2
	echo "       $0 [-p|--pass] [INFILE [OUTFILE]]" >&2
	exit 1
}

if [ $# -gt 0 ]
then
	[ "$1" = "-h" -o "$1" = "--help" ] && usage

	if [ "$1" = "-p" -o "$1" = "--pass" ]
	then
		DROP=""
		shift
		[ $# -gt 2 ] && usage
	else
		[ $# -gt 1 ] && usage
	fi
fi

SCRIPT="int C = 0;
	{ C = C + 1; $DROP }
	END { print C, \" total packets seen.\n\"; }"

if [ -z "$DROP" ]
then
	exec pml -e "$SCRIPT" $* 
else
	exec pml -e "$SCRIPT" $* 2>&1 >/dev/null
fi
