#!/bin/sh
#
# ONICS
# Copyright 2014-2015
# Christopher Adam Telfer
#
# pfind - Select packets from a packet file/stream.
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

IPATH=${IPATH:-}

getrange() {
	if echo $1 | grep '^[0-9][0-9]*$' > /dev/null 2>&1 
	then
		echo "N == $1"
	else
		echo "$*"
	fi
}


usage() {
	echo "usage: $0 PATTERN [INFILE [OUTFILE]]" >&2
	echo "       $0 <lo> -to <hi> [INFILE [OUTFILE]]" >&2
	exit 1

}

if [ $# -lt 1 -o $# -gt 5 -o "$1" = "-h" ]; then
	usage
fi


if [ $# -lt 3 -o "$2" != "-to" ]
then
	if [ $# -eq 2 -a "$2" = "-to" ]; then
		usage
	fi
	MATCH=`getrange $1`
	shift
	if [ "$2" = "-only" ] ; then shift ; fi
	exec pml $IPATH -ie "
		int N=0; 
		{ N=N+1; } 
		?- not ($MATCH) -? { drop; }
	" $*
else
	LO=`getrange $1`
	HI=`getrange $3`
	shift
	shift
	shift
	exec pml $IPATH -ie "
		int N = 0;
		int allow = 0;

		{ N = N + 1; }
		?- $LO -? { allow = 1; }
		?- allow -? { send_no_free 0; }
		?- $HI -? { allow = 0; drop; }
		{ drop; }
	" $*
fi
