#!/bin/sh
#
# ONICS
# Copyright 2016
# Christopher Adam Telfer
#
# pflt - find pakcets that only match the filter criteria
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

IPATH=${IPATH:-}

usage() {
	echo "usage: $0 PATTERN [INFILE [OUTFILE]]" >&2
	exit 1

}

if [ $# -lt 1 -o "$1" = "-h" ]; then
	usage
fi

MATCH=$1
shift
exec pml $IPATH -ie "?- not ($MATCH) -? { drop; }" $*
