#!/bin/sh

getrange() {
	if echo $1 | grep '^[0-9][0-9]*$' > /dev/null 2>&1 
	then
		echo "N == $1"
	else
		echo "$*"
	fi
}


usage() {
	echo "usage: $0 PATTERN [-only] [INFILE [OUTFILE]]" >&2
	echo "       $0 <lo> -to <hi> [INFILE [OUTFILE]]" >&2
	exit 1

}

if [ $# -lt 1 -o $# -gt 5 -o "$1" = "-h" ]; then
	usage
fi


if [ $# -lt 2 -o "$2" = "-only" ]
then
	MATCH=`getrange $1`
	shift
	if [ "$2" = "-only" ] ; then shift ; fi
	exec pml -e "
		import \"std.pml\";
		int N=0; 
		{ N=N+1; } 
		?- not ($MATCH) -? { drop; }
	" $*
else
	if [ $# -lt 3 -o "$2" != "-to" ]; then
		usage
	fi
	LO=`getrange $1`
	HI=`getrange $3`
	shift
	shift
	shift
	exec pml -e "
		import \"std.pml\";
		int N = 0;
		int allow = 0;

		{ N = N + 1; }
		?- $LO -? { allow = 1; }
		?- allow -? { send_no_free 0; }
		?- $HI -? { allow = 0; drop; }
		{ drop; }
	" $*
fi
