#!/bin/sh

getrange() {
	if echo $1 | grep '^[0-9][0-9]*$' > /dev/null 2>&1 
	then
		echo "P == $1"
	else
		echo "$*"
	fi
}


if [ $# -lt 1 -o $# -gt 3 -o "$1" = "-h" ]
then
	echo "usage: $0 PATTERN [INFILE [OUTFILE]]" >&2
	echo "       $0 <lo>[::<hi>] [INFILE [OUTFILE]]" >&2
	exit 1
fi


if ! echo $1 | grep :: > /dev/null 2>&1
then
	MATCH=`getrange $1`
	shift
	exec pml -e "
		int P=0; 
		{ P=P+1; } 
		?- not ($MATCH) -? { drop; }
	" $*
else
	LO=`echo $1 | sed -e 's/::.*$//'`
	HI=`echo $1 | sed -e 's/^.*:://'`
	shift
	exec pml -e "
		int P = 0;
		int allow = 0;

		{ P = P + 1; }
		?- $LO -? { allow = 1; }
		?- allow -? { send_no_free 0; }
		?- $HI -? { allow = 0; drop; }
		{ drop; }
	" $*
fi
