#!/bin/sh

if [ $# -gt 0 ]
then
	if [ "$1" = "-h" -o "$1" = "--help" ]
	then
		echo usage $0 "[starting sequence #]" >&2
		echo
		exit 1
	fi
	S=$1
else
	S=1
fi


pml -e "int P = $S; { meta_set_seq(0,P); P=P+1; }"

