#!/bin/sh
#
# ONICS
# Copyright 2013-2015
# Christopher Adam Telfer
#
# xpktdump - dump an xpkt stream out in readable format using pagination
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ "x$PAGER" = "x" ]
then
	PAGER=less
fi

OPTS=

if [ $# -gt 0 -a "x$1" = "x-x" ]
then
	OPTS="-x"
	shift
fi

if [ $# -gt 1 ] || [ $# -eq 1 -a "x$1" = "x-h" ]
then
	echo "usage: $0 [-x] [INFILE]" >&2
	exit 1
fi

x2hpkt $OPTS $* | $PAGER
