#ifndef __ncltok_h
#define __ncltok_h
#include "tokenizer.h"

enum {
  NCLTOK_EOF = TKZ_EOF,
  NCLTOK_ID  = TKZ_ID,
  NCLTOK_STRING = TKZ_STRING,
  NCLTOK_NUM = TKZ_NUM,
  NCLTOK_BYTESTR  = TKZ_BYTESTR,
  
  NCLTOK_NOT,
  NCLTOK_AND,
  NCLTOK_OR,

  NCLTOK_EQ,
  NCLTOK_NEQ,
  NCLTOK_LT,
  NCLTOK_GT,
  NCLTOK_LEQ,
  NCLTOK_GEQ,
  NCLTOK_MEQ,
  NCLTOK_SLT,
  NCLTOK_SGT,
  NCLTOK_SLEQ,
  NCLTOK_SGEQ,
  NCLTOK_REX,
  
  NCLTOK_PLUS,
  NCLTOK_MINUS,
  NCLTOK_TIMES,
  NCLTOK_DIV,
  NCLTOK_MOD,
  NCLTOK_BAND,
  NCLTOK_BOR,
  NCLTOK_BINV,
  NCLTOK_SHL,
  NCLTOK_SHR,
  NCLTOK_SHRA,
  NCLTOK_DOT,
  NCLTOK_COLON,
  
  NCLTOK_LBRACE,
  NCLTOK_RBRACE,
  NCLTOK_LPAREN,
  NCLTOK_RPAREN,
  NCLTOK_LBRACKET,
  NCLTOK_RBRACKET,
  NCLTOK_PPBEGIN,
  NCLTOK_PPEND,
  NCLTOK_COMMA,
};

#endif /* __ncltok_h */

